### ISSUE TITLE
GsonSpeaker and FastJsonSpeaker 

### ISSUE THREAD

**Issue by zengcanxiang** [VictorAlbertos/Jolyglot#6]
GsonSpeaker implements JolyglotGenerics，but,FastJsonSpeaker implements Jolyglot.
RxCache.Builder() .persistence() not do FastJsonSpeaker ?

**Comment by VictorAlbertos** [comment]
A json provider, in order to conform with [JolyglotGenerics](https://github.com/VictorAlbertos/Jolyglot/blob/master/api/src/main/java/io/victoralbertos/jolyglot/JolyglotGenerics.java) interface, requires to be able to implement this interface at 100%.  

The way to ensure this, it's running the [associated unit test](https://github.com/VictorAlbertos/Jolyglot/blob/master/api/src/test/java/io/victoralbertos/jolyglot/JolyglotGenericsTest.java).

When I added FastJson as a json provider to the Jolyglot library, I wasn't able to provide a right implementation for JolyglotGenerics with a 100% test success. That's why FastJson only conforms with [Jolyglot](https://github.com/VictorAlbertos/Jolyglot/blob/master/api/src/main/java/io/victoralbertos/jolyglot/Jolyglot.java) interface. 

If you are able to achieve this, please send a PR and I'll be very happy to include support for generics with FastJson :)
